# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_3 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_home = QtWidgets.QPushButton(self.dockWidgetContents_3)
        self.pushButton_home.setFlat(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.horizontalLayout.addWidget(self.pushButton_home)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeView = QtWidgets.QTreeView(self.splitter)
        self.treeView.setRootIsDecorated(False)
        self.treeView.setHeaderHidden(False)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.splitter)
        self.textEdit = Qsci.QsciScintilla(self.dockWidgetContents_3)
        self.textEdit.setToolTip("")
        self.textEdit.setWhatsThis("")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_3)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget_2 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.viewHours = QtWidgets.QListWidget(self.dockWidgetContents_2)
        self.viewHours.setEnabled(True)
        self.viewHours.setObjectName("viewHours")
        self.gridLayout.addWidget(self.viewHours, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.pushButton_readLogs = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_readLogs.setEnabled(False)
        self.pushButton_readLogs.setObjectName("pushButton_readLogs")
        self.gridLayout.addWidget(self.pushButton_readLogs, 1, 0, 1, 1)
        self.pushButton_readPoSAR = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButton_readPoSAR.setEnabled(False)
        self.pushButton_readPoSAR.setObjectName("pushButton_readPoSAR")
        self.gridLayout.addWidget(self.pushButton_readPoSAR, 2, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.dockWidget_8 = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget_8.setObjectName("dockWidget_8")
        self.dockWidgetContents_8 = QtWidgets.QWidget()
        self.dockWidgetContents_8.setObjectName("dockWidgetContents_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dockWidgetContents_8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit_logging = QtWidgets.QTextEdit(self.dockWidgetContents_8)
        self.textEdit_logging.setReadOnly(True)
        self.textEdit_logging.setObjectName("textEdit_logging")
        self.verticalLayout_2.addWidget(self.textEdit_logging)
        self.pushButton_clear_logs = QtWidgets.QPushButton(self.dockWidgetContents_8)
        self.pushButton_clear_logs.setObjectName("pushButton_clear_logs")
        self.verticalLayout_2.addWidget(self.pushButton_clear_logs)
        self.dockWidget_8.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_8)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_home.setText(_translate("MainWindow", "-"))
        self.groupBox.setTitle(_translate("MainWindow", "Actions"))
        self.pushButton_readLogs.setText(_translate("MainWindow", "Read SBG logs"))
        self.pushButton_readPoSAR.setText(_translate("MainWindow", "Read PoSAR"))
        self.pushButton_clear_logs.setText(_translate("MainWindow", "Clear"))
from PyQt5 import Qsci
